### PR TITLE
Fix for #10 : enhanced detection for some binary streams and UTF texts

### PR DESCRIPTION
**Pull request by pombredanne**
This pull request does a few things:
- it refines the heuristics to treat bytes above and below 127 differently.
- it introduces `chardet` as dependency (from Mark Pilgrim originally an now maintained by @dan-blanchard and with contributions from @sigmavirus24 and several others). For several less travelled character encodings that may use nulls or high bytes, this ensures we can detect these correctly as text.
- finally it adds tests for #10 proper and several more borrowed from @gjtorikian https://github.com/gjtorikian/isBinaryFile

### CODE REVIEW

**Comment by audreyr** [comment]
Thanks for all your work on this @pombredanne. Want to take a look at the errors on 2.6 and 3.3?

(Also, just fyi I added 3.4 to the .travis.yml on master.)

**Comment by pombredanne** [comment]
@audreyr wrote:
> Want to take a look at the errors on 2.6 and 3.3?

I will check these.

**Comment by pombredanne** [comment]
@audreyr I rebased on the latest master to get the new travis build.

**Comment by pombredanne** [comment]
@audreyr all set... a tad devilish though

**Comment by pombredanne** [comment]
@audreyr I can squash and rebase if you want a cleaner commit history

**Comment by audreyr** [comment]
Great work, thanks much for this @pombredanne!

**Pull request merged**
